import type { Lead } from './types'

export const sampleLeads: Lead[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    email: 'rajesh.kumar@gmail.com',
    source: 'facebook',
    category: 'hot',
    stage: 'interested',
    attempts: 3,
    lastContact: new Date('2024-01-15'),
    nextFollowUp: new Date('2024-01-18'),
    notes: 'Interested in 3BHK, budget 1.2Cr. Prefers east-facing.',
    whatsAppSent: true,
    createdAt: new Date('2024-01-10'),
    documents: {
      aadhaar: true,
      pan: true,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: true,
      addressProof: false,
    },
  },
  {
    id: '2',
    name: 'Priya Sharma',
    phone: '+91 87654 32109',
    email: 'priya.sharma@outlook.com',
    source: 'instagram',
    category: 'warm',
    stage: 'visit-scheduled',
    attempts: 2,
    lastContact: new Date('2024-01-14'),
    nextFollowUp: new Date('2024-01-17'),
    notes: 'Site visit scheduled for Sunday 11 AM',
    whatsAppSent: true,
    createdAt: new Date('2024-01-08'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
  {
    id: '3',
    name: 'Amit Patel',
    phone: '+91 76543 21098',
    source: 'referral',
    category: 'hot',
    stage: 'docs-collected',
    attempts: 5,
    lastContact: new Date('2024-01-16'),
    nextFollowUp: new Date('2024-01-19'),
    notes: 'Ready to book. Awaiting loan approval.',
    whatsAppSent: true,
    createdAt: new Date('2024-01-01'),
    documents: {
      aadhaar: true,
      pan: true,
      salarySlip: true,
      bankStatement: true,
      itReturns: true,
      agreement: false,
      photo: true,
      addressProof: true,
    },
  },
  {
    id: '4',
    name: 'Sunita Reddy',
    phone: '+91 65432 10987',
    email: 'sunita.reddy@yahoo.com',
    source: 'facebook',
    category: 'cold',
    stage: 'new',
    attempts: 0,
    whatsAppSent: false,
    createdAt: new Date('2024-01-16'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
  {
    id: '5',
    name: 'Vikram Singh',
    phone: '+91 54321 09876',
    source: 'excel',
    category: 'warm',
    stage: 'contacted',
    attempts: 1,
    lastContact: new Date('2024-01-15'),
    nextFollowUp: new Date('2024-01-16'),
    notes: 'Interested in investment property',
    whatsAppSent: true,
    createdAt: new Date('2024-01-12'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
  {
    id: '6',
    name: 'Meera Nair',
    phone: '+91 43210 98765',
    email: 'meera.nair@gmail.com',
    source: 'instagram',
    category: 'hot',
    stage: 'visit-done',
    attempts: 4,
    lastContact: new Date('2024-01-14'),
    nextFollowUp: new Date('2024-01-17'),
    notes: 'Loved the property. Wants corner unit.',
    whatsAppSent: true,
    createdAt: new Date('2024-01-05'),
    documents: {
      aadhaar: true,
      pan: true,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: true,
      addressProof: false,
    },
  },
  {
    id: '7',
    name: 'Arjun Kapoor',
    phone: '+91 32109 87654',
    source: 'facebook',
    category: 'cold',
    stage: 'follow-up',
    attempts: 2,
    lastContact: new Date('2024-01-13'),
    nextFollowUp: new Date('2024-01-20'),
    notes: 'Budget constraints. May consider after 6 months.',
    whatsAppSent: true,
    createdAt: new Date('2024-01-09'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
  {
    id: '8',
    name: 'Deepika Menon',
    phone: '+91 21098 76543',
    email: 'deepika.menon@hotmail.com',
    source: 'referral',
    category: 'warm',
    stage: 'new',
    attempts: 0,
    whatsAppSent: false,
    createdAt: new Date('2024-01-16'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
  {
    id: '9',
    name: 'Rohit Gupta',
    phone: '+91 10987 65432',
    source: 'excel',
    category: 'warm',
    stage: 'lost',
    attempts: 6,
    lastContact: new Date('2024-01-10'),
    notes: 'Bought from competitor. Good prospect for future projects.',
    whatsAppSent: true,
    createdAt: new Date('2023-12-15'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
  {
    id: '10',
    name: 'Kavita Joshi',
    phone: '+91 09876 54321',
    email: 'kavita.joshi@gmail.com',
    source: 'instagram',
    category: 'cold',
    stage: 'lost',
    attempts: 4,
    lastContact: new Date('2024-01-08'),
    notes: 'Not interested anymore. Location too far from workplace.',
    whatsAppSent: true,
    createdAt: new Date('2023-12-20'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
  {
    id: '11',
    name: 'Sanjay Malhotra',
    phone: '+91 98123 45678',
    source: 'facebook',
    category: 'hot',
    stage: 'closed-won',
    attempts: 5,
    lastContact: new Date('2024-01-12'),
    notes: 'Booked 2BHK in Tower B. Payment plan: 20-80.',
    whatsAppSent: true,
    createdAt: new Date('2023-11-25'),
    documents: {
      aadhaar: true,
      pan: true,
      salarySlip: true,
      bankStatement: true,
      itReturns: true,
      agreement: true,
      photo: true,
      addressProof: true,
    },
  },
  {
    id: '12',
    name: 'Neha Verma',
    phone: '+91 87123 45678',
    email: 'neha.verma@company.com',
    source: 'referral',
    category: 'cold',
    stage: 'lost',
    attempts: 3,
    lastContact: new Date('2024-01-05'),
    notes: 'Postponed purchase plans due to job change.',
    whatsAppSent: true,
    createdAt: new Date('2023-12-28'),
    documents: {
      aadhaar: false,
      pan: false,
      salarySlip: false,
      bankStatement: false,
      itReturns: false,
      agreement: false,
      photo: false,
      addressProof: false,
    },
  },
]
